stages:
  - test
  - cleanup

test:
  stage: test
  script:
    - sed -i "s|http://www.example.com/|${TEST_URL}/|g" tests/acceptance.suite.yml
    - make all

cleanup:
  stage: cleanup
  script:
    - make clean